domain: <deine domain>
email: <deine email>

traefik_domain: traefik.<deine domain>
auth_domain: auth.<deine domain>
grafana_domain: grafana.<deine domain>

letsencrypt_resolver: le
timezone: Europe/Berlin
