---
- command: docker --version
  register: docker_check
  ignore_errors: yes
  changed_when: false

- set_fact:
    docker_installed: "{{ docker_check.rc == 0 }}"

- include_tasks: install.yml
  when: not docker_installed

- include_tasks: validate.yml
