---
- hosts: all
  become: yes
  tasks:
    - apt:
        name: [ufw, fail2ban]
        update_cache: yes
        
    - shell: ufw deny all
    - shell: ufw allow 22,80,443/tcp
    - shell: ufw --force enable
