name: Deploy Bocker Cluster

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ansible-playbook playbooks/01-docker-hardened.yml


      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-playbook playbooks/01-docker-safe.yml
          ansible-playbook playbooks/02-swarm-cluster.yml

        name: Deploy


